# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "buildingInterface" ]
  pull_request:
    branches: [ "buildingInterface" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      working-directory: ./project files
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install coverage
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Testing initialisation with unittest
      working-directory: ./project files
      run: |
        python -m coverage run -m unittest -v testInit.py
    - name: Testing the game logic with unittest
      working-directory: ./project files
      run: |
        python -m coverage run -m unittest -v testGameLogic.py
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
